Repository HYF-Class20/agile-development-group5-loruki, pull requests merged in 2023-04, with the labels that each got.

#6 adding first user persona
  planning/user-personas.md
Labels: documentation

#9 User personas 2
  planning/backlog.md
  planning/user-personas.md
Labels: team, md, planning

#7 add backlog
  planning/backlog.md
Labels: backlog, team

#18 info of development-strategy
  planning/development-strategy.md
Labels: documentation

#14 update retrospective.md
  planning/retrospective.md
Labels: documentation, md

#21 updated user personas and added img
  planning/design.md
  planning/figmadesign.png
  planning/freelance-web-developer.png
  planning/user-personas.md
Labels: documentation

#24 update-backlog
  planning/backlog.md
Labels: md
